package net.silencily.sailing.basic.sm.domain;

import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblCmnRole generated by hbm2java
 */
public class TblCmnSysParameter extends EntityPlus implements java.io.Serializable {
	
	private String parameterSign;
	
	private String parameterValue;
	
	private String parameterNote;
	
	public TblCmnSysParameter()
	{
		
	}

	public String getParameterSign() {
		return parameterSign;
	}

	public void setParameterSign(String parameterSign) {
		this.parameterSign = parameterSign;
	}

	public String getParameterValue() {
		return parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	public String getParameterNote() {
		return parameterNote;
	}

	public void setParameterNote(String parameterNote) {
		this.parameterNote = parameterNote;
	}
	
	
}
