package net.silencily.sailing.basic.sm.domain;

// Generated 2007-11-14 16:40:27 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnUserRole generated by hbm2java
 */
public class TblCmnUserRole extends EntityPlus implements java.io.Serializable {

	private TblCmnUser tblCmnUser;

	private TblCmnRole tblCmnRole;

	private TblCmnUser tblCmnUserByConsignerId;

	private Date beginTime;

	private Date invalidTime;

	public TblCmnUserRole() {
	}


	public TblCmnUser getTblCmnUser() {
		return this.tblCmnUser;
	}

	public void setTblCmnUser(TblCmnUser tblCmnUser) {
		this.tblCmnUser = tblCmnUser;
	}

	public TblCmnRole getTblCmnRole() {
		return this.tblCmnRole;
	}

	public void setTblCmnRole(TblCmnRole tblCmnRole) {
		this.tblCmnRole = tblCmnRole;
	}


	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getInvalidTime() {
		return this.invalidTime;
	}

	public void setInvalidTime(Date invalidTime) {
		this.invalidTime = invalidTime;
	}


	public TblCmnUser getTblCmnUserByConsignerId() {
		return tblCmnUserByConsignerId;
	}


	public void setTblCmnUserByConsignerId(TblCmnUser tblCmnUserByConsignerId) {
		this.tblCmnUserByConsignerId = tblCmnUserByConsignerId;
	}


}
