package net.silencily.sailing.basic.sm.domain;

// Generated 2007-11-14 16:40:27 by Hibernate Tools 3.2.0.b9

import java.util.HashMap;
import java.util.Map;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnMsgConfig generated by hbm2java
 */
public class TblCmnMsgConfig extends EntityPlus implements java.io.Serializable {

	private static Map messageMap = new HashMap();
	static {
		messageMap.put("1", "ÊÇ");
		messageMap.put("0", "·ñ");
	}

	private TblCmnUser tblCmnUser;

	private String userSign;

	private String imService;

	private String imSign;

	private String emailService;

	private String emailSign;

	private String smsService;

	private String smsSign;

	public TblCmnMsgConfig() {
	}

	public TblCmnUser getTblCmnUser() {
		return this.tblCmnUser;
	}

	public void setTblCmnUser(TblCmnUser tblCmnUser) {
		this.tblCmnUser = tblCmnUser;
	}

	public String getUserSign() {
		return this.userSign;
	}

	public void setUserSign(String userSign) {
		this.userSign = userSign;
	}

	public String getImService() {
		return this.imService;
	}

	public void setImService(String imService) {
		this.imService = imService;
	}

	public String getImSign() {
		return this.imSign;
	}

	public void setImSign(String imSign) {
		this.imSign = imSign;
	}

	public String getEmailService() {
		return this.emailService;
	}

	public void setEmailService(String emailService) {
		this.emailService = emailService;
	}

	public String getEmailSign() {
		return this.emailSign;
	}

	public void setEmailSign(String emailSign) {
		this.emailSign = emailSign;
	}

	public String getSmsService() {
		return this.smsService;
	}

	public void setSmsService(String smsService) {
		this.smsService = smsService;
	}

	public String getSmsSign() {
		return this.smsSign;
	}

	public void setSmsSign(String smsSign) {
		this.smsSign = smsSign;
	}

	public static Map getMessageMap() {
		return messageMap;
	}

	public static void setMessageMap(Map messageMap) {
		TblCmnMsgConfig.messageMap = messageMap;
	}

}
