package net.silencily.sailing.basic.sm.domain;

// Generated 2007-11-14 16:40:27 by Hibernate Tools 3.2.0.b9

import java.util.Date;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnSysLog generated by hbm2java
 */
public class TblCmnSysLog extends EntityPlus implements java.io.Serializable {

	private String msgSign;

	private Date time;

	private String empCd;

	private String userName;

	private String funName;

	private String operate;

	private String jobSign;


	public TblCmnSysLog() {
	}


	public String getMsgSign() {
		return this.msgSign;
	}

	public void setMsgSign(String msgSign) {
		this.msgSign = msgSign;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public String getOperate() {
		return this.operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	public String getJobSign() {
		return this.jobSign;
	}

	public void setJobSign(String jobSign) {
		this.jobSign = jobSign;
	}


	public String getEmpCd() {
		return empCd;
	}


	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}


	public Date getTime() {
		return time;
	}


	public void setTime(Date time) {
		this.time = time;
	}

	public String getStringTime() {
		return time.toString();
		
	}
}
