package net.silencily.sailing.common.crud.domain;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * CommonTableScreen generated by MyEclipse Persistence Tools
 */
public class CommonTableScreen extends EntityPlus implements
		java.io.Serializable {

	private String screenName;
	private String tableName;

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getScreenName() {
		return screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}
}
