package net.silencily.sailing.basic.uf.domain;

import java.util.Date;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblUfSsoEntry generated by MyEclipse Persistence Tools
 */

public class TblUfSsoEntry extends EntityPlus
        implements java.io.Serializable {

	// Fields

	private String empCd;
	private String url;
	private Long accessableTimes;
	private Date invalidTime;

	// Constructors

	/** default constructor */
	public TblUfSsoEntry() {
	}

	// Property accessors

	public String getEmpCd() {
		return this.empCd;
	}

	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getAccessableTimes() {
		return this.accessableTimes;
	}

	public void setAccessableTimes(Long accessableTimes) {
		this.accessableTimes = accessableTimes;
	}

	public Date getInvalidTime() {
		return this.invalidTime;
	}

	public void setInvalidTime(Date invalidTime) {
		this.invalidTime = invalidTime;
	}

}