package net.silencily.sailing.basic.uf.domain;

import net.silencily.sailing.basic.sm.domain.TblCmnUser;
import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblUfColumnOrder generated by MyEclipse Persistence Tools
 */

public class TblUfPubPermission extends EntityPlus implements
		java.io.Serializable {

	// Fields
	 
	private TblUfColumn tblUfColumn;

//	private String empCd;

    private TblCmnUser tblHrEmpInfo;

	// Property accessors
	 
	public TblUfColumn getTblUfColumn() {
		return this.tblUfColumn;
	}

	public void setTblUfColumn(TblUfColumn tblUfColumn) {
		this.tblUfColumn = tblUfColumn;
	}

//	public String getEmpCd() {
//		return this.empCd;
//	}
//
//	public void setEmpCd(String empCd) {
//		this.empCd = empCd;
//	}

    /**
     * @return tblHrEmpInfo
     */
    public TblCmnUser getTblHrEmpInfo() {
        return tblHrEmpInfo;
    }

    /**
     * @param tblHrEmpInfo ÒªÉèÖÃµÄ tblHrEmpInfo
     */
    public void setTblHrEmpInfo(TblCmnUser tblHrEmpInfo) {
        this.tblHrEmpInfo = tblHrEmpInfo;
    }

}