package net.silencily.sailing.basic.uf.domain;

import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblUfColumnOrder generated by MyEclipse Persistence Tools
 */

public class TblUfColumnOrder extends EntityPlus implements
		java.io.Serializable {

	// Fields

	 
	private TblUfColumn tblUfColumn;

	private String empCd;

	private String isSelect;

	private String displaySort;

	// Property accessors

	 
	public TblUfColumn getTblUfColumn() {
		return this.tblUfColumn;
	}

	public void setTblUfColumn(TblUfColumn tblUfColumn) {
		this.tblUfColumn = tblUfColumn;
	}

	public String getEmpCd() {
		return this.empCd;
	}

	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}

	public String getIsSelect() {
		return this.isSelect;
	}

	public void setIsSelect(String isSelect) {
		this.isSelect = isSelect;
	}

	public String getDisplaySort() {
		return this.displaySort;
	}

	public void setDisplaySort(String displaySort) {
		this.displaySort = displaySort;
	}


}