package net.silencily.sailing.basic.wf.domain;
// default package

import net.silencily.sailing.basic.wf.dto.BisWfEntry;



/**
 * TblWfEditInfo generated by MyEclipse - Hibernate Tools
 */

public class TblWfEditInfo  extends BisWfEntry implements java.io.Serializable {


    // Fields    
     private String fieldCodeEdit;
     private String fieldNameEdit;
     private String tblWfName;
     private String tblWfOperName;
     private String remark;


    // Constructors

    /** default constructor */
    public TblWfEditInfo() {
    }

    
    /** full constructor */
    /*public TblWfEditInfo(String fieldCodeEdit, String fieldNameEdit, String tblWfName, String tblWfOperName, String remark) {
        this.fieldCodeEdit = fieldCodeEdit;
        this.fieldNameEdit = fieldNameEdit;
        this.tblWfName = tblWfName;
        this.tblWfOperName = tblWfOperName;
        this.remark = remark;
    }*/

   
    // Property accessors

    public String getFieldCodeEdit() {
        return this.fieldCodeEdit;
    }
    
    public void setFieldCodeEdit(String fieldCodeEdit) {
        this.fieldCodeEdit = fieldCodeEdit;
    }

    public String getFieldNameEdit() {
        return this.fieldNameEdit;
    }
    
    public void setFieldNameEdit(String fieldNameEdit) {
        this.fieldNameEdit = fieldNameEdit;
    }

    public String getTblWfName() {
        return this.tblWfName;
    }
    
    public void setTblWfName(String tblWfName) {
        this.tblWfName = tblWfName;
    }

    public String getTblWfOperName() {
        return this.tblWfOperName;
    }
    
    public void setTblWfOperName(String tblWfOperName) {
        this.tblWfOperName = tblWfOperName;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


	public String getWorkflowEditPath(String oid) {
		// TODO Auto-generated method stub
		return null;
	}


	public String getWorkflowName() {
		// TODO Auto-generated method stub
		return null;
	}


	public String getTaskName(String title) {
		// TODO Auto-generated method stub
		return null;
	}
}
