package net.silencily.sailing.basic.wf.domain;

import java.util.Date;

/**
 * TblWfFormInfo generated by MyEclipse Persistence Tools
 */

public class TblWfFormInfo implements java.io.Serializable {

	// Fields

	private String id;

	private TblWfParticularInfo tblWfParticularInfo;

	private String fieldCode;

	private String fieldName;

	private String tblWfOpeInfId;

	private String editor;

	private String delFlg;

	private Integer version;

	private Long sequenceNo;

	private String creator;

	private String creatorDept;

	private Date createdTime;

	private String modifier;

	private String modifierDept;

	private Date modifiedTime;

	private String deleter;

	private String deleterDept;

	private Date deletedTime;
	
	private String editorFlg;

	// Constructors

	public String getEditorFlg() {
		return editorFlg;
	}

	public void setEditorFlg(String editorFlg) {
		this.editorFlg = editorFlg;
	}

	/** default constructor */
	public TblWfFormInfo() {
	}

	/** minimal constructor */
	public TblWfFormInfo(TblWfParticularInfo tblWfParticularInfo,
			String fieldCode, String fieldName, String tblWfOpeInfId) {
		this.tblWfParticularInfo = tblWfParticularInfo;
		this.fieldCode = fieldCode;
		this.fieldName = fieldName;
		this.tblWfOpeInfId = tblWfOpeInfId;
	}

	/** full constructor */
	public TblWfFormInfo(TblWfParticularInfo tblWfParticularInfo,
			String fieldCode, String fieldName, String tblWfOpeInfId,
			String editor, String delFlg, Integer version, Long sequenceNo,
			String creator, String creatorDept, Date createdTime,
			String modifier, String modifierDept, Date modifiedTime,
			String deleter, String deleterDept, Date deletedTime) {
		this.tblWfParticularInfo = tblWfParticularInfo;
		this.fieldCode = fieldCode;
		this.fieldName = fieldName;
		this.tblWfOpeInfId = tblWfOpeInfId;
		this.editor = editor;
		this.delFlg = delFlg;
		this.version = version;
		this.sequenceNo = sequenceNo;
		this.creator = creator;
		this.creatorDept = creatorDept;
		this.createdTime = createdTime;
		this.modifier = modifier;
		this.modifierDept = modifierDept;
		this.modifiedTime = modifiedTime;
		this.deleter = deleter;
		this.deleterDept = deleterDept;
		this.deletedTime = deletedTime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TblWfParticularInfo getTblWfParticularInfo() {
		return this.tblWfParticularInfo;
	}

	public void setTblWfParticularInfo(TblWfParticularInfo tblWfParticularInfo) {
		this.tblWfParticularInfo = tblWfParticularInfo;
	}

	public String getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(String fieldCode) {
		this.fieldCode = fieldCode;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getTblWfOpeInfId() {
		return this.tblWfOpeInfId;
	}

	public void setTblWfOpeInfId(String tblWfOpeInfId) {
		this.tblWfOpeInfId = tblWfOpeInfId;
	}

	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public String getDelFlg() {
		return this.delFlg;
	}

	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Long getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getCreatorDept() {
		return this.creatorDept;
	}

	public void setCreatorDept(String creatorDept) {
		this.creatorDept = creatorDept;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public String getModifierDept() {
		return this.modifierDept;
	}

	public void setModifierDept(String modifierDept) {
		this.modifierDept = modifierDept;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getDeleter() {
		return this.deleter;
	}

	public void setDeleter(String deleter) {
		this.deleter = deleter;
	}

	public String getDeleterDept() {
		return this.deleterDept;
	}

	public void setDeleterDept(String deleterDept) {
		this.deleterDept = deleterDept;
	}

	public Date getDeletedTime() {
		return this.deletedTime;
	}

	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

}