package net.silencily.sailing.basic.sm.domain;

// Generated 2007-11-14 16:40:27 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.silencily.sailing.basic.sm.role.service.RoleService;
import net.silencily.sailing.common.domain.tree.FlatTreeNode;
import net.silencily.sailing.container.ServiceProvider;
import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnRole generated by hbm2java
 */
public class TblCmnRole extends EntityPlus implements FlatTreeNode,
		java.io.Serializable {

	private static Map systemRoleMap = new HashMap();
	static {
		systemRoleMap.put("0", "否");
		systemRoleMap.put("1", "是");
	}

	private TblCmnRoleOrg father;

	private String roleCd;

	private String name;

	private String note;

	private Short displayOrder;

	private String systemRoleName;

	private String systemRole;

	private String roleRoute;

	private static RoleService service() {
		return (RoleService) ServiceProvider
				.getService(RoleService.SERVICE_NAME);
	}

	private Set tblCmnRolePermissions = new HashSet(0);

	private Set tblCmnUserRoles = new HashSet(0);

	public TblCmnRole() {
	}

	public String getRoleCd() {
		return this.roleCd;
	}

	public void setRoleCd(String roleCd) {
		this.roleCd = roleCd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	public String getSystemRole() {
		return this.systemRole;
	}

	public void setSystemRole(String systemRole) {
		this.systemRole = systemRole;
	}

	public Set getTblCmnRolePermissions() {
		return this.tblCmnRolePermissions;
	}

	public void setTblCmnRolePermissions(Set tblCmnRolePermissions) {
		this.tblCmnRolePermissions = tblCmnRolePermissions;
	}

	public Set getTblCmnUserRoles() {
		return this.tblCmnUserRoles;
	}

	public void setTblCmnUserRoles(Set tblCmnUserRoles) {
		this.tblCmnUserRoles = tblCmnUserRoles;
	}

	/**
	 * 当前节点是否是根节点
	 * 
	 * @return 如果这个实例是根节点返回<code>true</code>
	 */
	public boolean isRootNode() {
		return false;
	}

	/**
	 * 检索这个节点的标题
	 * 
	 * @return 这个节点的标题
	 */
	public String getCaptain() {

		return this.getName();
	}

	/**
	 * 返回当前节点表示的数据信息, 经常是一个<code>domain object</code>, 可以返回<code>null</code>
	 * 
	 * @return 当前节点表示的数据信息
	 */
	public Object getData() {
		return this;
	}

	/**
	 * 检索唯一标识这个节点的<code>identity</code>, 在一些实现中可能是<code>url</code>, 具体的值 取决于实现
	 * 
	 * @return 标识这个节点的<code>identity</code>
	 */
	public String getIdentity() {
		return getId();
	}

	/**
	 * 得到 ui 上显示的图片类型 ?
	 * 
	 * @return the image Type
	 */
	public String getImageType() {
		return "2";
	}

	/**
	 * 此节点展示到 ui 上时是否可选, 默认应该为 true
	 * 
	 * @return whether this node can be selected from ui
	 */
	public boolean isCanbeSelected() {
		return true;
	}

	/**
	 * 当前节点是否有子节点, 与 {@link #isLeaf()} 不同, 它真正描述了该节点下是否有子节点, 与业务无关
	 * 
	 * @return whether has children
	 */
	public boolean isHasChildren() {
		return false;
	}

	/**
	 * 当前节点是否是<code>leaf</code>节点, 通常一个节点不允许有子节点才返回<code>true</code>,
	 * 这个描述一般是业务含义上的, 如果一个非叶子节点没有子节点这个方法返回<code>false</code>, 只是
	 * <code>hasChildren() == true</code>
	 * 
	 * @return 如果是<code>leaf</code>节点返回<code>true</code>, 否则<code>false</code>
	 */
	public boolean isLeaf() {
		return true;
	}

	public TblCmnRoleOrg getFather() {
		return father;
	}

	public void setFather(TblCmnRoleOrg father) {
		this.father = father;
	}

	/**
	 * 
	 * 功能描述 取得角色路径
	 * 
	 * @return 2007-11-23 下午08:08:14
	 * @version 1.0
	 * @author baihe
	 */
	public String getRoleRoute() {
		String route = this.name;
		while (father != null) {
			route = father.getDisplayName() + "/" + route;
			father = father.getFather();
		}
		return route;
	}

	public void setRoleRoute(String roleRoute) {
		this.roleRoute = roleRoute;
	}

	public static Map getSystemRoleMap() {
		return systemRoleMap;
	}

	public static void setSystemRoleMap(Map systemRoleMap) {
		TblCmnRole.systemRoleMap = systemRoleMap;
	}

	public String getSystemRoleName() {
		return (String) systemRoleMap.get(systemRole);
	}

	public void setSystemRoleName(String systemRoleName) {
		this.systemRoleName = systemRoleName;
	}
}
