package net.silencily.sailing.basic.sm.domain;

// Generated 2007-11-14 16:40:27 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import net.silencily.sailing.common.crud.service.CommonService;
import net.silencily.sailing.container.ServiceProvider;
import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnUser generated by hbm2java
 */
public class TblCmnUser extends EntityPlus implements java.io.Serializable {
	
	private static Map statusMap = new HashMap();
	static{
		statusMap.put("0", "禁用");
		statusMap.put("1", "激活");
	}
	private String password;
	
	private String empCd;
	
	private String empName;

	private CodeWrapperPlus sex;

	private CodeWrapperPlus nation;

	private Date birthday;

	private String homePlace;

	private String nativePlace;

	private String idCard;
	
	private String failedTimes;

	private String status;
	
	private String deptRoute;
	
	private TblCmnDept tblCmnDept;
	
	private String electricalSign;
	
	private CodeWrapperPlus affiliateSpecialty;

	private Set roles = new HashSet(0);

	private Set consigneUserPermissions = new HashSet(0);
	
	private Set consigneUserRoles = new HashSet(0);

	private Set userPermissions= new HashSet(0);

	private Set msgConfigs = new HashSet(0);
	
	private Set tblCmnUserMember = new HashSet(0);

	public Set getTblCmnUserMember() {
		return tblCmnUserMember;
	}

	public void setTblCmnUserMember(Set tblCmnUserMember) {
		this.tblCmnUserMember = tblCmnUserMember;
	}

	public TblCmnUser() {
	}

	public String getStatusName()
	{
		return (String)statusMap.get(status);
	}
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getMsgConfigs() {
		return msgConfigs;
	}


	public void setMsgConfigs(Set msgConfigs) {
		this.msgConfigs = msgConfigs;
	}


	public Set getRoles() {
		return roles;
	}


	public void setRoles(Set roles) {
		this.roles = roles;
	}


	public Set getConsigneUserPermissions() {
		return consigneUserPermissions;
	}


	public void setConsigneUserPermissions(Set consigneUserPermissions) {
		this.consigneUserPermissions = consigneUserPermissions;
	}


	public Set getUserPermissions() {
		return userPermissions;
	}


	public void setUserPermissions(Set userPermissions) {
		this.userPermissions = userPermissions;
	}

	public static Map getStatusMap() {
		return statusMap;
	}


	public static void setStatusMap(Map statusMap) {
		TblCmnUser.statusMap = statusMap;
	}
	private CommonService getService() {
		return (CommonService)ServiceProvider.getService(CommonService.SERVICE_NAME);
	}

	public Set getConsigneUserRoles() {
		return consigneUserRoles;
	}

	public void setConsigneUserRoles(Set consigneUserRoles) {
		this.consigneUserRoles = consigneUserRoles;
	}

	public String getFailedTimes() {
		return failedTimes;
	}

	public void setFailedTimes(String failedTimes) {
		this.failedTimes = failedTimes;
	}

	public TblCmnDept getTblCmnDept() {
	    if (tblCmnDept == null)
	        tblCmnDept = new TblCmnDept();
		return tblCmnDept;
	}

	public void setTblCmnDept(TblCmnDept tblCmnDept) {
		this.tblCmnDept = tblCmnDept;
	}

	/**
	 * 
	 * 功能描述 取得部门路径
	 * @return
	 * 2007-11-23 下午08:11:04
	 * @version 1.0
	 * @author baihe
	 */
	public String getDeptRoute() {
           
		String deptRoute=tblCmnDept.getDeptName();
			while(tblCmnDept.getParent()!=null){
				tblCmnDept=tblCmnDept.getParent();
			deptRoute = tblCmnDept.getDeptName() + "/" + deptRoute;
		}
		return deptRoute;
	}


	public void setDeptRoute(String deptRoute) {
		this.deptRoute = deptRoute;
	}
	
	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getHomePlace() {
		return homePlace;
	}

	public void setHomePlace(String homePlace) {
		this.homePlace = homePlace;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public CodeWrapperPlus getNation() {
		if (nation == null)
			nation = new CodeWrapperPlus();
		return nation;
	}

	public void setNation(CodeWrapperPlus nation) {
		this.nation = nation;
	}

	public String getNativePlace() {
		return nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	public CodeWrapperPlus getSex() {
		if (sex == null)
			sex = new CodeWrapperPlus();
		return sex;
	}

	public void setSex(CodeWrapperPlus sex) {
		this.sex = sex;
	}

	public String getEmpCd() {
		return empCd;
	}

	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}
	
	public String getElectricalSign() {
		return electricalSign;
	}

	public void setElectricalSign(String electricalSign) {
		this.electricalSign = electricalSign;
	}
	
	public CodeWrapperPlus getAffiliateSpecialty() {
		if (affiliateSpecialty == null) {
			affiliateSpecialty = new CodeWrapperPlus();
		}
		return affiliateSpecialty;
	}

	public void setAffiliateSpecialty(CodeWrapperPlus affiliateSpecialty) {
		this.affiliateSpecialty = affiliateSpecialty;
	}

}
