package net.silencily.sailing.basic.sm.domain;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import net.silencily.sailing.common.domain.tree.FlatTreeNode;
import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;

/**
 * TblCmnDept generated by MyEclipse Persistence Tools
 */

public class TblCmnDept extends EntityPlus implements FlatTreeNode {

	public static final String ROOT_NODE_CODE = "root";

	private String parentId;

	private String deptCd;

	private String deptName;

	private String telephone;

	private String fax;

	private String email;

	private String webAdress;

	private CodeWrapperPlus isGroup;

	private Integer expectPerson;

	private String deptCharge;

	private CodeWrapperPlus deptProperty;

	private String deptState;

	private String deptAddress;

	private Integer showSequence;

	private String memorabilia;

	private String remark;

	private String field1;

	private String field2;

	private String field3;

	private String field4;

	private String field5;

	private Set tblCmnUsers = new HashSet(0);

	private Set tblCmnDeptPareRecs = new HashSet(0);

	private Set tblCmnDeptStatusRecs = new HashSet(0);

	/** 如果这个值不是<code>null</code>, 这个属性就是当前节点的上级节点 */
	private TblCmnDept parent;

	/** 当前节点的直接子节点, 元素类型也是{@link TCmnDept} */
	private List children = new ArrayList();

	// - utility methods
	/**
	 * 判断当前配置节点是否是叶子节点
	 * 
	 * @return 如果是叶子节点返回<code>true</code>
	 */
	public boolean isLeaf() {
		return getChildren().isEmpty();
	}

	/**
	 * 当前节点是否是根节点
	 * 
	 * @return 如果这个实例是根节点返回<code>true</code>
	 */
	public boolean isRootNode() {
		return ROOT_NODE_CODE.equals(getDeptCd());// 部门编码
	}

	// - getters & setters
	/** default constructor */
	public TblCmnDept() {
	}

	/**
	 * @return the deptAddress
	 */
	public String getDeptAddress() {
		return deptAddress;
	}

	/**
	 * @param deptAddress
	 *            the deptAddress to set
	 */
	public void setDeptAddress(String deptAddress) {
		this.deptAddress = deptAddress;
	}

	/**
	 * @return the deptCd
	 */
	public String getDeptCd() {
		return deptCd;
	}

	/**
	 * @param deptCd
	 *            the deptCd to set
	 */
	public void setDeptCd(String deptCd) {
		this.deptCd = deptCd;
	}

	/**
	 * @return the deptCharge
	 */
	public String getDeptCharge() {
		return deptCharge;
	}

	/**
	 * @param deptCharge
	 *            the deptCharge to set
	 */
	public void setDeptCharge(String deptCharge) {
		this.deptCharge = deptCharge;
	}

	/**
	 * @return the deptName
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * @param deptName
	 *            the deptName to set
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * @return the deptState
	 */
	public String getDeptState() {
		return deptState;
	}

	/**
	 * @param deptState
	 *            the deptState to set
	 */
	public void setDeptState(String deptState) {
		this.deptState = deptState;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email
	 *            the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the expectPerson
	 */
	public Integer getExpectPerson() {
		return expectPerson;
	}

	/**
	 * @param expectPerson
	 *            the expectPerson to set
	 */
	public void setExpectPerson(Integer expectPerson) {
		this.expectPerson = expectPerson;
	}

	/**
	 * @return the fax
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * @param fax
	 *            the fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return field1;
	}

	/**
	 * @param field1
	 *            the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return field2;
	}

	/**
	 * @param field2
	 *            the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the field3
	 */
	public String getField3() {
		return field3;
	}

	/**
	 * @param field3
	 *            the field3 to set
	 */
	public void setField3(String field3) {
		this.field3 = field3;
	}

	/**
	 * @return the field4
	 */
	public String getField4() {
		return field4;
	}

	/**
	 * @param field4
	 *            the field4 to set
	 */
	public void setField4(String field4) {
		this.field4 = field4;
	}

	/**
	 * @return the field5
	 */
	public String getField5() {
		return field5;
	}

	/**
	 * @param field5
	 *            the field5 to set
	 */
	public void setField5(String field5) {
		this.field5 = field5;
	}

	/**
	 * @return the deptProperty
	 */
	public CodeWrapperPlus getDeptProperty() {
		if (deptProperty == null)
			deptProperty = new CodeWrapperPlus();
		return deptProperty;
	}

	/**
	 * @param deptProperty
	 *            the deptProperty to set
	 */
	public void setDeptProperty(CodeWrapperPlus deptProperty) {
		this.deptProperty = deptProperty;
	}

	/**
	 * @return the isGroup
	 */
	public CodeWrapperPlus getIsGroup() {
		if (isGroup == null)
			isGroup = new CodeWrapperPlus();
		return isGroup;
	}

	/**
	 * @param isGroup
	 *            the isGroup to set
	 */
	public void setIsGroup(CodeWrapperPlus isGroup) {
		this.isGroup = isGroup;
	}

	/**
	 * @return the memorabilia
	 */
	public String getMemorabilia() {
		return memorabilia;
	}

	/**
	 * @param memorabilia
	 *            the memorabilia to set
	 */
	public void setMemorabilia(String memorabilia) {
		this.memorabilia = memorabilia;
	}

	/**
	 * @return the parentId
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * @param parentId
	 *            the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return the remark
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark
	 *            the remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * @return the showSequence
	 */
	public Integer getShowSequence() {
		return showSequence;
	}

	/**
	 * @param showSequence
	 *            the showSequence to set
	 */
	public void setShowSequence(Integer showSequence) {
		this.showSequence = showSequence;
	}

	/**
	 * @return the tblCmnDeptPareRecs
	 */
	public Set getTblCmnDeptPareRecs() {
		return tblCmnDeptPareRecs;
	}

	/**
	 * @param tblCmnDeptPareRecs
	 *            the tblCmnDeptPareRecs to set
	 */
	public void setTblCmnDeptPareRecs(Set tblCmnDeptPareRecs) {
		this.tblCmnDeptPareRecs = tblCmnDeptPareRecs;
	}

	/**
	 * @return the tblCmnDeptStatusRecs
	 */
	public Set getTblCmnDeptStatusRecs() {
		return tblCmnDeptStatusRecs;
	}

	/**
	 * @param tblCmnDeptStatusRecs
	 *            the tblCmnDeptStatusRecs to set
	 */
	public void setTblCmnDeptStatusRecs(Set tblCmnDeptStatusRecs) {
		this.tblCmnDeptStatusRecs = tblCmnDeptStatusRecs;
	}

	/**
	 * @return the telephone
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * @param telephone
	 *            the telephone to set
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * @return the webAdress
	 */
	public String getWebAdress() {
		return webAdress;
	}

	/**
	 * @param webAdress
	 *            the webAdress to set
	 */
	public void setWebAdress(String webAdress) {
		this.webAdress = webAdress;
	}

	// ----------------
	public String getCaptain() {
		return getDeptName();
	}

	public Object getData() {
		return this;
	}

	public String getIdentity() {
		return getId();
	}

	public String getImageType() {
		return isRootNode() ? "0" : isLeaf() ? "2" : "1";
	}

	public boolean isCanbeSelected() {
		return true;
	}

	public boolean isHasChildren() {
		return getChildren().size() > 0;
	}

	public static String getROOT_NODE_CODE() {
		return ROOT_NODE_CODE;
	}

	public List getChildren() {
		return children;
	}

	public void setChildren(List children) {
		this.children = children;
	}

	public TblCmnDept getParent() {
		return parent;
	}

	public void setParent(TblCmnDept parent) {
		this.parent = parent;
	}

	/**
	 * @return the tblCmnEmpInfos
	 */
	public Set getTblCmnUsers() {
		return tblCmnUsers;
	}

	/**
	 * @param tblCmnEmpInfos
	 *            the tblCmnEmpInfos to set
	 */
	public void setTblCmnUsers(Set tblCmnUsers) {
		this.tblCmnUsers = tblCmnUsers;
	}

}