package net.silencily.sailing.basic.uf.domain;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblUfColumn generated by MyEclipse Persistence Tools
 */

public class TblUfColumn extends EntityPlus implements
		java.io.Serializable {

	// Fields

	private String columnNm;

    private CodeWrapperPlus columnFlg;

    private CodeWrapperPlus feedbackFlg;

//    private Set wfe;	
    
	private List tblUfNewses = new ArrayList();

	private Set tblUfColumnOrders = new HashSet(0);

    private Set tblUfPubPermission = new HashSet(0);
    
//    private List scheduleList = new ArrayList();

	// Property accessors


	public String getColumnNm() {
		return this.columnNm;
	}

	public void setColumnNm(String columnNm) {
		this.columnNm = columnNm;
	}

    public CodeWrapperPlus getFeedbackFlg() {
        if (this.feedbackFlg == null) {
            this.feedbackFlg = new CodeWrapperPlus();
            this.feedbackFlg.setCode("0");
        }
        return this.feedbackFlg;
    }

    public void setFeedbackFlg(CodeWrapperPlus feedbackFlg) {
        this.feedbackFlg = feedbackFlg;
    }

    public void setFeedbackFlg(String feedbackFlg) {
        this.feedbackFlg = new CodeWrapperPlus();
        this.feedbackFlg.setCode(feedbackFlg);
    }

    public List getTblUfNewses() {
		return this.tblUfNewses;
	}

	public void setTblUfNewses(List tblUfNewses) {
		this.tblUfNewses = tblUfNewses;
	}

	public Set getTblUfColumnOrders() {
		return this.tblUfColumnOrders;
	}

	public void setTblUfColumnOrders(Set tblUfColumnOrders) {
		this.tblUfColumnOrders = tblUfColumnOrders;
	}

//	public Set getWfe() {
//		return wfe;
//	}
//
//	public void setWfe(Set wfe) {
//		this.wfe = wfe;
//	}

    public Set getTblUfPubPermission() {
        return this.tblUfPubPermission;
    }

    public void setTblUfPubPermission(Set tblUfPubPermission) {
        this.tblUfPubPermission = tblUfPubPermission;
    }

    public CodeWrapperPlus getColumnFlg() {
        if (this.columnFlg == null)
            this.columnFlg = new CodeWrapperPlus();
        return this.columnFlg;
    }

    public void setColumnFlg(CodeWrapperPlus columnFlg) {
        this.columnFlg = columnFlg;
    }

    public void setColumnFlg(String columnFlg) {
        this.columnFlg = new CodeWrapperPlus();
        this.columnFlg.setCode(columnFlg);
    }

//	public List getScheduleList() {
//		return scheduleList;
//	}
//
//	public void setScheduleList(List scheduleList) {
//		this.scheduleList = scheduleList;
//	}
}