package net.silencily.sailing.basic.uf.domain;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import net.silencily.sailing.common.dbtime.DBTime;
import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;
import net.silencily.sailing.security.SecurityContextInfo;

import org.apache.commons.lang.StringUtils;

/**
 * TblUfNews generated by MyEclipse Persistence Tools
 */

public class TblUfNews extends EntityPlus implements
		java.io.Serializable {

	// Fields

	 
	private TblUfColumn tblUfColumn;

	private String title;

	private String content;

	private Date publishTime;

	private String author;

	private String publisherId;

	private String keyword;

    private String source;

    private CodeWrapperPlus recommend;

	private CodeWrapperPlus published;

	private Date invalidTime;

	private String imptLvl;

	private String sendAllFlg;

	private String feedbackFlg;

	private Set tblUfNewsFdbks = new HashSet(0);

    private Set tblUfNewsAttach = new HashSet(0);

    private String myFeedback;

    //发布人的姓名
    private String publisherName;
 
    public TblUfColumn getTblUfColumn() {
		return this.tblUfColumn;
	}

	public void setTblUfColumn(TblUfColumn tblUfColumn) {
		if (tblUfColumn == null) tblUfColumn = new TblUfColumn();
		this.tblUfColumn = tblUfColumn;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublisherId() {
		return this.publisherId;
	}

	public void setPublisherId(String publisherId) {
		this.publisherId = publisherId;
	}

	public String getImptLvl() {
		return this.imptLvl;
	}

	public void setImptLvl(String imptLvl) {
		this.imptLvl = imptLvl;
	}

	public String getSendAllFlg() {
		return this.sendAllFlg;
	}

	public void setSendAllFlg(String sendAllFlg) {
		this.sendAllFlg = sendAllFlg;
	}

	public String getFeedbackFlg() {
		return this.feedbackFlg;
	}

	public void setFeedbackFlg(String feedbackFlg) {
		this.feedbackFlg = feedbackFlg;
	}

    public Set getTblUfNewsFdbks() {
		return this.tblUfNewsFdbks;
	}

	public void setTblUfNewsFdbks(Set tblUfNewsFdbks) {
		this.tblUfNewsFdbks = tblUfNewsFdbks;
	}

    public String getSpublishTime() {
        if (this.publishTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(DBTime.getDBTime());
        if (today.equals(sdf.format(this.publishTime))) {
            sdf = new SimpleDateFormat("HH:mm");
            return sdf.format(this.publishTime);
        } else {
            sdf = new SimpleDateFormat("MM-dd");
            return sdf.format(this.publishTime);
        }
    }

    public CodeWrapperPlus getRecommend() {
        if (this.recommend == null) {
            this.recommend = new CodeWrapperPlus();
            this.recommend.setCode("0");
        }
        return this.recommend;
    }

    public void setRecommend(CodeWrapperPlus recommend) {
        this.recommend = recommend;
    }

    public void setRecommend(String recommend) {
        this.recommend = new CodeWrapperPlus();
        this.recommend.setCode(recommend);
    }

    public CodeWrapperPlus getPublished() {
        if (this.published == null) {
            this.published = new CodeWrapperPlus();
            this.published.setCode("0");
        }
        return this.published;
    }

    public void setPublished(CodeWrapperPlus published) {
        this.published = published;
    }

    public void setPublished(String published) {
        this.published = new CodeWrapperPlus();
        this.published.setCode(published);
    }

	public Date getInvalidTime() {
		return invalidTime;
	}

	public void setInvalidTime(Date invalidTime) {
		this.invalidTime = invalidTime;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    /**
     * @return the tblUfNewsAttach
     */
    public Set getTblUfNewsAttach() {
        return tblUfNewsAttach;
    }

    /**
     * @param tblUfNewsAttach the tblUfNewsAttach to set
     */
    public void setTblUfNewsAttach(Set tblUfNewsAttach) {
        this.tblUfNewsAttach = tblUfNewsAttach;
    }

    /**
     * @return 是否可编辑
     */
    public boolean getCanEdit() {
        if (!"1".equals(this.getPublished().getCode())) {
            //未发布则可编辑
            return true;
        }
        Calendar nowDate = Calendar.getInstance();
        nowDate.clear(Calendar.MILLISECOND);
        nowDate.clear(Calendar.SECOND);
        nowDate.clear(Calendar.MINUTE);
        nowDate.clear(Calendar.HOUR);
        nowDate.clear(Calendar.HOUR_OF_DAY);
        Date dt = nowDate.getTime();
        if (dt.after(this.getInvalidTime())) {
            //过期则可编辑
            return true;
        }
        return false;
    }

    /**
     * @return 是否可编辑
     */
    public String getMyFeedback() {
        if (this.myFeedback != null) {
            return this.myFeedback;
        }
        String feedbackFlg = this.tblUfColumn.getFeedbackFlg().getCode();
        if ("1".equals(feedbackFlg)) {
            String empCd = SecurityContextInfo.getCurrentUser().getEmpCd();
            for (Iterator iter = tblUfNewsFdbks.iterator(); iter.hasNext();) {
                TblUfNewsFdbk fdbk = (TblUfNewsFdbk) iter.next();
                if (fdbk.getTblHrEmpInfo().getEmpCd().equals(empCd)) {
                    if (StringUtils.isBlank(fdbk.getFeedback())) {
                        this.myFeedback = "";
                        return this.myFeedback;
                    } else {
                        this.myFeedback = fdbk.getFeedback();
                        return this.myFeedback;
                    }
                }
            }
        }
        this.myFeedback = "";
        return this.myFeedback;
    }

	public String getPublisherName() {
		return publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}
}