package net.silencily.sailing.basic.uf.domain;

import net.silencily.sailing.basic.sm.domain.TblCmnUser;
import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblUfNewsFdbk generated by MyEclipse Persistence Tools
 */

public class TblUfNewsFdbk extends EntityPlus implements
		java.io.Serializable {

	// Fields

 
	private TblUfNews tblUfNews;

	private String empCd;
	
	private TblCmnUser tblHrEmpInfo;

	private String feedbackSta;
	
    private String feedback;

    // Property accessors

 
	public TblUfNews getTblUfNews() {
		return this.tblUfNews;
	}

	public void setTblUfNews(TblUfNews tblUfNews) {
		this.tblUfNews = tblUfNews;
	}

	public String getEmpCd() {
		return this.empCd;
	}

	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}

	public String getFeedbackSta() {
		return this.feedbackSta;
	}

	public void setFeedbackSta(String feedbackSta) {
		this.feedbackSta = feedbackSta;
	}

    public String getFeedback() {
        return this.feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    /**
	 * @return tblHrEmpInfo
	 */
	public TblCmnUser getTblHrEmpInfo() {
		return tblHrEmpInfo;
	}

	/**
	 * @param tblHrEmpInfo ÒªÉèÖÃµÄ tblHrEmpInfo
	 */
	public void setTblHrEmpInfo(TblCmnUser tblHrEmpInfo) {
		this.tblHrEmpInfo = tblHrEmpInfo;
	}
}