package net.silencily.sailing.basic.uf.domain;

// Generated 2007-12-6 10:41:11 by Hibernate Tools 3.2.0.b9

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import net.silencily.sailing.common.dbtime.DBTime;
import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblUfSchedule generated by hbm2java
 */
public class TblUfSchedule extends EntityPlus implements java.io.Serializable {
	public TblUfSchedule() {
	}
	private String empCd;

	private String messageId;
	
	private Date begTime;

	private Date endTime;

	private String title;

	private String content;

	private CodeWrapperPlus alertTyp;

	private String alertTime;

	private String reptAlert;

	private CodeWrapperPlus completeFlg;

	public String getEmpCd() {
		return this.empCd;
	}

	public void setEmpCd(String empCd) {
		this.empCd = empCd;
	}

	public Date getBegTime() {
		return this.begTime;
	}

	public void setBegTime(Date begTime) {
		this.begTime = begTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public CodeWrapperPlus getAlertTyp() {
		if(alertTyp == null)
		{
			alertTyp = new CodeWrapperPlus();
		}
		return this.alertTyp;
	}

	public void setAlertTyp(CodeWrapperPlus alertTyp) {
		this.alertTyp = alertTyp;
	}

	public String getAlertTime() {
		return this.alertTime;
	}

	public void setAlertTime(String alertTime) {
		this.alertTime = alertTime;
	}

	public String getReptAlert() {
		return this.reptAlert;
	}

	public void setReptAlert(String reptAlert) {
		this.reptAlert = reptAlert;
	}

	public CodeWrapperPlus getCompleteFlg() {
		if(completeFlg == null)
		{
			completeFlg = new CodeWrapperPlus();
		}
		return this.completeFlg;
	}

	public void setCompleteFlg(CodeWrapperPlus completeFlg) {
		this.completeFlg = completeFlg;
	}

	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

    public String getDisplayTime() {
        if (this.begTime == null) {
            return "";
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(DBTime.getDBTime());
        if (today.equals(sdf.format(this.begTime))) {
            sdf = new SimpleDateFormat("HH:mm");
            return sdf.format(this.begTime);
        } else {
            sdf = new SimpleDateFormat("MM-dd");
            return sdf.format(this.begTime);
        }
    }
}