package net.silencily.sailing.autokey.domain;

/**
 * CommonKey generated by MyEclipse Persistence Tools
 */

public class CommonKey extends net.silencily.sailing.hibernate3.EntityPlus
		implements java.io.Serializable {

	// Fields

	private Long codeNum;
	private String codeStr;
	private String remark;

	// Constructors

	/** default constructor */
	public CommonKey() {
	}

	public void autoGain() {
		codeNum = new Long(codeNum.longValue() + 1);
	}

	public void decrease() {
		if (codeNum.longValue() > 1)
			codeNum = new Long(codeNum.longValue() - 1);
	}

	public Long getCodeNum() {
		return this.codeNum;
	}

	public void setCodeNum(Long codeNum) {
		this.codeNum = codeNum;
	}

	public String getCodeStr() {
		return this.codeStr;
	}

	public void setCodeStr(String codeStr) {
		this.codeStr = codeStr;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}