package net.silencily.sailing.common.dict.domain;


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import net.silencily.sailing.common.domain.tree.FlatTreeNode;
import net.silencily.sailing.hibernate3.EntityPlus;



/**
 * HrBasiccode generated by MyEclipse Persistence Tools
 */

public class CommonBasicCode extends EntityPlus implements FlatTreeNode {

	public static final String ROOT_NODE_CODE = "root";
	// Fields

	
	/** 如果这个值不是<code>null</code>, 这个属性就是当前节点的上级节点 */
	private CommonBasicCode parent;
	
	/** 当前节点的直接子节点, 元素类型也是{@link THrConfiguration} */
	private List children = new ArrayList();
	private String subid;

	private String typeCode;

	private String displayName;

	

	private String name;

	private String code;

	private String codeDesc;

	private Integer showSequence;

	private Long currentLayer;

	private String deleteState="1";

	private String operator;

	private Date operateTime;
	
	private Integer layerNum;

	private String field1;

	private String field2;

	private String field3;

	private String field4;

	private String field5;

	// Constructors

	/** default constructor */
	public CommonBasicCode() {
	}

	

	


	public String getSubid() {
		return this.subid;
	}

	public void setSubid(String subid) {
		this.subid = subid;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}





	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	

	/**
	 * @return the showSequence
	 */
	public Integer getShowSequence() {
		return showSequence;
	}

	/**
	 * @param showSequence the showSequence to set
	 */
	public void setShowSequence(Integer showSequence) {
		this.showSequence = showSequence;
	}

	public Long getCurrentLayer() {
		return this.currentLayer;
	}

	public void setCurrentLayer(Long currentLayer) {
		this.currentLayer = currentLayer;
	}

	public String getDeleteState() {
		return this.deleteState;
	}

	public void setDeleteState(String deleteState) {
		this.deleteState = deleteState;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	public String getField4() {
		return this.field4;
	}

	public void setField4(String field4) {
		this.field4 = field4;
	}

	public String getField5() {
		return this.field5;
	}

	public void setField5(String field5) {
		this.field5 = field5;
	}

	public String getCaptain() {
		return this.getName();
	}

	public Object getData() {
		return this;
	}

	public String getIdentity() {
		// TODO Auto-generated method stub
		return this.getId();
	}

	public String getImageType() {
		// TODO Auto-generated method stub
		return isRootNode() ? "0" : isLeaf() ? "2" : "1";
	}

	public boolean isCanbeSelected() {
		// TODO Auto-generated method stub
		return true;
	}

	public boolean isHasChildren() {
		// TODO Auto-generated method stub
		return getChildren().size() > 0;
	}

	/**
	 * 判断当前配置节点是否是叶子节点
	 * @return 如果是叶子节点返回<code>true</code>
	 */
	public boolean isLeaf() {
		return getChildren().isEmpty();
	}

	public List getChildren() {
		return children;
	}

	public void setChildren(List children) {
		this.children = children;
	}

	public CommonBasicCode getParent() {
		if(parent==null)
			parent=new CommonBasicCode();
		return parent;
	}
	
	public void setParent(CommonBasicCode parent) {
		this.parent = parent;
		//this.setLayerNum(new Integer(parent.getLayerNum().intValue()+1));
	}

	/**
	 * 当前节点是否是根节点
	 * @return 如果这个实例是根节点返回<code>true</code>
	 */
	public boolean isRootNode() {
		return ROOT_NODE_CODE.equals(getCode());
	}






	public Integer getLayerNum() {
		return layerNum;
	}






	public void setLayerNum(Integer layerNum) {
		this.layerNum = layerNum;
	}

}