package net.silencily.sailing.basic.wf.domain;

import java.util.HashSet;
import java.util.Set;

import net.silencily.sailing.hibernate3.CodeWrapperPlus;
import net.silencily.sailing.hibernate3.EntityPlus;


/**
 * TblWfOperationInfo generated by MyEclipse Persistence Tools
 */

public class TblWfOperationInfo extends EntityPlus
		implements java.io.Serializable {

	// Fields
	private CodeWrapperPlus wftype; // 流程类型；

	private String name; // 流程名称；

	private Double edition; // 流程版本；

	private CodeWrapperPlus status; // 流程状态；

	private String code;

	private String tblName;

	private String operName; // 业务名称；

	private String stepNum; // 步骤数量；

	private Set tblWfParticularInfos = new HashSet(0);

	private String pointStep;

	private String className; // 持久化类型；

	private String flowManager; // 流程管理员；

	// Constructors

	public String getFlowManager() {
		return flowManager;
	}

	public void setFlowManager(String flowManager) {
		this.flowManager = flowManager;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getPointStep() {
		return pointStep;
	}

	public void setPointStep(String pointStep) {
		this.pointStep = pointStep;
	}

	// Property accessors

	public CodeWrapperPlus getWftype() {
		if (wftype == null)
			wftype = new CodeWrapperPlus();
		return wftype;
	}

	public void setWftype(CodeWrapperPlus wftype) {
		this.wftype = wftype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getEdition() {
		return this.edition;
	}

	public void setEdition(Double edition) {
		this.edition = edition;
	}

	public CodeWrapperPlus getStatus() {
		if (status == null)
			status = new CodeWrapperPlus();
		return status;
	}

	public void setStatus(CodeWrapperPlus status) {
		this.status = status;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTblName() {
		return this.tblName;
	}

	public void setTblName(String tblName) {
		this.tblName = tblName;
	}

	public String getOperName() {
		return this.operName;
	}

	public void setOperName(String operName) {
		this.operName = operName;
	}

	public String getStepNum() {
		return this.stepNum;
	}

	public void setStepNum(String stepNum) {
		this.stepNum = stepNum;
	}

	public Set getTblWfParticularInfos() {
		return this.tblWfParticularInfos;
	}

	public void setTblWfParticularInfos(Set tblWfParticularInfos) {
		this.tblWfParticularInfos = tblWfParticularInfos;
	}

}