package net.silencily.sailing.basic.wf.domain;

import java.util.Date;

/**
 * TblWfUsersign generated by MyEclipse Persistence Tools
 */

public class TblWfUsersign implements java.io.Serializable {

	// Fields

	private String id;

	private String osworkflowid;

	private String processed;

	private String processId;

	private String processUsername;

	private String processRole;

	private String processTime;

	private String processRemark;

	private String processSort;

	private String commitUsername;

	private String commitRole;

	private String commitId;

	private Date commitTime;

	private String delFlg;

	private String version;

	private String sequenceNo;

	private String creator;

	private String creatorDept;

	private Date createdTime;

	private String modifier;

	private String modifierDept;

	private Date modifiedTime;

	private String deleter;

	private String deleterDept;

	private Date deletedTime;

	private String processDept;

	private String commitDept;

	private String oid;

	private String workflowName;

	private String currStepId;

	private String currStepName;

	private String toStepId;

	private String toStepName;

	private String roleSignFlag;

	private String roleSignRole;

	private String roleSignDept;

	private String consignFlag;

	private String consignedFlag;

	private String consigner;

	private String consigneder;

	private String consignerRole;

	private String consignederRole;

	private String className;

	private String consignerId;

	private String consignederId;

	// Constructors

	/** default constructor */
	public TblWfUsersign() {
	}

	/** minimal constructor */
	public TblWfUsersign(String oid, String workflowName, String currStepId,
			String currStepName) {
		this.oid = oid;
		this.workflowName = workflowName;
		this.currStepId = currStepId;
		this.currStepName = currStepName;
	}

	/** full constructor */
	public TblWfUsersign(String osworkflowid, String processed,
			String processId, String processUsername, String processRole,
			String processTime, String processRemark, String processSort,
			String commitUsername, String commitRole, String commitId,
			Date commitTime, String delFlg, String version, String sequenceNo,
			String creator, String creatorDept, Date createdTime,
			String modifier, String modifierDept, Date modifiedTime,
			String deleter, String deleterDept, Date deletedTime,
			String processDept, String commitDept, String oid,
			String workflowName, String currStepId, String currStepName,
			String toStepId, String toStepName, String roleSignFlag,
			String roleSignRole, String roleSignDept, String consignFlag,
			String consignedFlag, String consigner, String consigneder,
			String consignerRole, String consignederRole, String className,
			String consignerId, String consignederId) {
		this.osworkflowid = osworkflowid;
		this.processed = processed;
		this.processId = processId;
		this.processUsername = processUsername;
		this.processRole = processRole;
		this.processTime = processTime;
		this.processRemark = processRemark;
		this.processSort = processSort;
		this.commitUsername = commitUsername;
		this.commitRole = commitRole;
		this.commitId = commitId;
		this.commitTime = commitTime;
		this.delFlg = delFlg;
		this.version = version;
		this.sequenceNo = sequenceNo;
		this.creator = creator;
		this.creatorDept = creatorDept;
		this.createdTime = createdTime;
		this.modifier = modifier;
		this.modifierDept = modifierDept;
		this.modifiedTime = modifiedTime;
		this.deleter = deleter;
		this.deleterDept = deleterDept;
		this.deletedTime = deletedTime;
		this.processDept = processDept;
		this.commitDept = commitDept;
		this.oid = oid;
		this.workflowName = workflowName;
		this.currStepId = currStepId;
		this.currStepName = currStepName;
		this.toStepId = toStepId;
		this.toStepName = toStepName;
		this.roleSignFlag = roleSignFlag;
		this.roleSignRole = roleSignRole;
		this.roleSignDept = roleSignDept;
		this.consignFlag = consignFlag;
		this.consignedFlag = consignedFlag;
		this.consigner = consigner;
		this.consigneder = consigneder;
		this.consignerRole = consignerRole;
		this.consignederRole = consignederRole;
		this.className = className;
		this.consignerId = consignerId;
		this.consignederId = consignederId;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOsworkflowid() {
		return this.osworkflowid;
	}

	public void setOsworkflowid(String osworkflowid) {
		this.osworkflowid = osworkflowid;
	}

	public String getProcessed() {
		return this.processed;
	}

	public void setProcessed(String processed) {
		this.processed = processed;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getProcessUsername() {
		return this.processUsername;
	}

	public void setProcessUsername(String processUsername) {
		this.processUsername = processUsername;
	}

	public String getProcessRole() {
		return this.processRole;
	}

	public void setProcessRole(String processRole) {
		this.processRole = processRole;
	}

	public String getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(String processTime) {
		this.processTime = processTime;
	}

	public String getProcessRemark() {
		return this.processRemark;
	}

	public void setProcessRemark(String processRemark) {
		this.processRemark = processRemark;
	}

	public String getProcessSort() {
		return this.processSort;
	}

	public void setProcessSort(String processSort) {
		this.processSort = processSort;
	}

	public String getCommitUsername() {
		return this.commitUsername;
	}

	public void setCommitUsername(String commitUsername) {
		this.commitUsername = commitUsername;
	}

	public String getCommitRole() {
		return this.commitRole;
	}

	public void setCommitRole(String commitRole) {
		this.commitRole = commitRole;
	}

	public String getCommitId() {
		return this.commitId;
	}

	public void setCommitId(String commitId) {
		this.commitId = commitId;
	}

	public Date getCommitTime() {
		return this.commitTime;
	}

	public void setCommitTime(Date commitTime) {
		this.commitTime = commitTime;
	}

	public String getDelFlg() {
		return this.delFlg;
	}

	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(String sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getCreatorDept() {
		return this.creatorDept;
	}

	public void setCreatorDept(String creatorDept) {
		this.creatorDept = creatorDept;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public String getModifierDept() {
		return this.modifierDept;
	}

	public void setModifierDept(String modifierDept) {
		this.modifierDept = modifierDept;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public String getDeleter() {
		return this.deleter;
	}

	public void setDeleter(String deleter) {
		this.deleter = deleter;
	}

	public String getDeleterDept() {
		return this.deleterDept;
	}

	public void setDeleterDept(String deleterDept) {
		this.deleterDept = deleterDept;
	}

	public Date getDeletedTime() {
		return this.deletedTime;
	}

	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

	public String getProcessDept() {
		return this.processDept;
	}

	public void setProcessDept(String processDept) {
		this.processDept = processDept;
	}

	public String getCommitDept() {
		return this.commitDept;
	}

	public void setCommitDept(String commitDept) {
		this.commitDept = commitDept;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getWorkflowName() {
		return this.workflowName;
	}

	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	public String getCurrStepId() {
		return this.currStepId;
	}

	public void setCurrStepId(String currStepId) {
		this.currStepId = currStepId;
	}

	public String getCurrStepName() {
		return this.currStepName;
	}

	public void setCurrStepName(String currStepName) {
		this.currStepName = currStepName;
	}

	public String getToStepId() {
		return this.toStepId;
	}

	public void setToStepId(String toStepId) {
		this.toStepId = toStepId;
	}

	public String getToStepName() {
		return this.toStepName;
	}

	public void setToStepName(String toStepName) {
		this.toStepName = toStepName;
	}

	public String getRoleSignFlag() {
		return this.roleSignFlag;
	}

	public void setRoleSignFlag(String roleSignFlag) {
		this.roleSignFlag = roleSignFlag;
	}

	public String getRoleSignRole() {
		return this.roleSignRole;
	}

	public void setRoleSignRole(String roleSignRole) {
		this.roleSignRole = roleSignRole;
	}

	public String getRoleSignDept() {
		return this.roleSignDept;
	}

	public void setRoleSignDept(String roleSignDept) {
		this.roleSignDept = roleSignDept;
	}

	public String getConsignFlag() {
		return this.consignFlag;
	}

	public void setConsignFlag(String consignFlag) {
		this.consignFlag = consignFlag;
	}

	public String getConsignedFlag() {
		return this.consignedFlag;
	}

	public void setConsignedFlag(String consignedFlag) {
		this.consignedFlag = consignedFlag;
	}

	public String getConsigner() {
		return this.consigner;
	}

	public void setConsigner(String consigner) {
		this.consigner = consigner;
	}

	public String getConsigneder() {
		return this.consigneder;
	}

	public void setConsigneder(String consigneder) {
		this.consigneder = consigneder;
	}

	public String getConsignerRole() {
		return this.consignerRole;
	}

	public void setConsignerRole(String consignerRole) {
		this.consignerRole = consignerRole;
	}

	public String getConsignederRole() {
		return this.consignederRole;
	}

	public void setConsignederRole(String consignederRole) {
		this.consignederRole = consignederRole;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getConsignerId() {
		return this.consignerId;
	}

	public void setConsignerId(String consignerId) {
		this.consignerId = consignerId;
	}

	public String getConsignederId() {
		return this.consignederId;
	}

	public void setConsignederId(String consignederId) {
		this.consignederId = consignederId;
	}

}